### PR TITLE
ADDED the 712.txt

### LINKED ISSUE #1433: Info of 712
please assign this to me.

### PR DESCRIPTION
**Pull request by adarsh1219**
please merge this in hactoberfest accepted.

### CODE REVIEW

**Comment by Xtha-Sunil** [comment]
PR is under review

**Comment by adarsh1219** [comment]
pr is passed

**Comment by adarsh1219** [comment]
now you can merge it

**Review by Xtha-Sunil — APPROVED** [review]

**Comment by Xtha-Sunil** [comment]
Your PR is merged with hacktoberfest-accepted label.
Thanks for contributing.

**Pull request merged**
